### ISSUE TITLE
Preview buggy when used from GIMP-2.9

### ISSUE THREAD

**Issue by Beep6581** [dtschump/gmic-community#10] opened 2015-08-07 14:39 UTC
Hey

GIMP's plug-in preview API hasn't changed in ages. Users of GIMP-2.9 would appreciate it very much if you could test GMIC on GIMP-2.9 and fix the little oddities which would lead to a far better user experience. Specifically, the preview (sometimes?) cannot be zoomed in/out, and sometimes the preview gets drawn off-canvas. You'll see what I mean when you try it.
http://i.imgur.com/ROcFXvA.png

**Comment by dtschump** [comment] 2015-08-07 14:42
Actually, G'MIC uses the default preview widget provided by the GIMP API.
I suspect a bug in the preview widget for 2.9 then, because we are not doing anything exotic with this preview widget (just get the image data, and update the view).
Not sure this is something I can fix easily.

**Comment by Beep6581** [comment] 2015-08-28 08:45
Reported here https://bugzilla.gnome.org/show_bug.cgi?id=754221

**Comment by dtschump** [comment] 2015-12-22 09:14
This has been fixed by the GIMP developers. There was a regression in the GimpPreview widget. I close this issue.

**Closed by dtschump** 2015-12-22 09:14 UTC

**Comment by Beep6581** [comment] 2015-12-23 13:07
Yes it works correctly now, thank you.
