### ISSUE TITLE
Guidlines to troubleshoot

### ISSUE THREAD

**Issue by francoisdejgr** [dtschump/gmic-community#41] opened 2016-03-17 08:59 UTC
Greetings
I have downloaded the gmic_win64.zip file and extracted to a folder.  Whenever I try to run the gmic.exe -h command in either powershell or cmd line I get a message that the program have crashed.
I don't think it is a bug but I have not other way to request information on what I can do to troubleshoot this issue.

Is there any log files or a way to force the system to generate log files so that I can troubleshoot?
System: Win 7 64

**Comment by dtschump** [comment] 2016-03-17 09:02
Well, what version of G'MIC did you download, the 1.6.9 (default download link) or 1.7.0_pre ?
Is there any significant error message displayed somewhere ?
It could be a problem with the DLL maybe ?
I'll check at the lab this afternoon to see if this is working for me (it should! :) ).

**Comment by francoisdejgr** [comment] 2016-03-17 09:08
Greetings

 

Thanks for the quick response.

I have downloaded the 1.6.9 – I prefer to stay away from development releases.

In the zip folder there is a sub folder - gmic-1.6.9-win64

 

The only message is a popup that states 



 

 

 

Francois de Jager

**Comment by dtschump** [comment] 2016-03-17 14:59
I've just tested on my windows7, and everything seems to run fine (even if a bit slower than on Linux).
I don't know what happen.
Maybe someone else with a similar problem can send suggestions ?

**Comment by jayprich** [comment] 2016-03-17 17:23
make sure you have extracted the whole zipfile before running it

if you double-click on just the exe (e.g. from viewing the zip as a folder)
then the necessary runtime dlls are not available .. usually however you'd
get a windows message about that

**Comment by francoisdejgr** [comment] 2016-03-18 08:07
Greetings

 

Thanks for trying to help

 

Here is some more info – hope it helps, but I am 100% sure there is something wrong on my pc, so you can close this case.

 

When I run gmic – h in a command window it scrolls to section 12 and the last sentence being:

QUOTE

   if you want to save and view images with the same 

aspect than those illustrated in the example codes.

UNQUOTE

 

From the windows event log I extracted the following report:

Version=1

EventType=APPCRASH

EventTime=131027613220114346

ReportType=2

Consent=1

UploadTime=131027613221124403

ReportIdentifier=c34ca96a-ecde-11e5-94bd-645a04c820e1

IntegratorReportIdentifier=c34ca969-ecde-11e5-94bd-645a04c820e1

Response.BucketId=176074141

Response.BucketTable=28

Response.type=4

Sig[0].Name=Application Name

Sig[0].Value=gmic.exe

Sig[1].Name=Application Version

Sig[1].Value=0.0.0.0

Sig[2].Name=Application Timestamp

Sig[2].Value=00000000

Sig[3].Name=Fault Module Name

Sig[3].Value=msvcrt.dll

Sig[4].Name=Fault Module Version

Sig[4].Value=7.0.7601.17744

Sig[5].Name=Fault Module Timestamp

Sig[5].Value=4eeb033f

Sig[6].Name=Exception Code

Sig[6].Value=c0000005

Sig[7].Name=Exception Offset

Sig[7].Value=000000000000116b

DynamicSig[1].Name=OS Version

DynamicSig[1].Value=6.1.7601.2.1.0.256.4

DynamicSig[2].Name=Locale ID

DynamicSig[2].Value=7177

DynamicSig[22].Name=Additional Information 1

DynamicSig[22].Value=2feb

DynamicSig[23].Name=Additional Information 2

DynamicSig[23].Value=2feb2ed136147c75392525a23ec20995

DynamicSig[24].Name=Additional Information 3

DynamicSig[24].Value=b6c3

DynamicSig[25].Name=Additional Information 4

DynamicSig[25].Value=b6c3cbe16b7964fabdb9f3375055c786

UI[2]=D:\image_processing\gmic\gmic_win64\gmic.exe

UI[3]=gmic.exe has stopped working

UI[4]=Windows can check online for a solution to the problem.

UI[5]=Check online for a solution and close the program

UI[6]=Check online for a solution later and close the program

UI[7]=Close the program

LoadedModule[0]=D:\image_processing\gmic\gmic_win64\gmic.exe

LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll

LoadedModule[2]=C:\Windows\system32\kernel32.dll

LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll

LoadedModule[4]=D:\image_processing\gmic\gmic_win64\libcurl-4.dll

LoadedModule[5]=D:\image_processing\gmic\gmic_win64\LIBEAY32.dll

LoadedModule[6]=C:\Windows\system32\ADVAPI32.dll

LoadedModule[7]=C:\Windows\system32\msvcrt.dll

LoadedModule[8]=C:\Windows\SYSTEM32\sechost.dll

LoadedModule[9]=C:\Windows\system32\RPCRT4.dll

LoadedModule[10]=C:\Windows\system32\GDI32.dll

LoadedModule[11]=C:\Windows\system32\USER32.dll

LoadedModule[12]=C:\Windows\system32\LPK.dll

LoadedModule[13]=C:\Windows\system32\USP10.dll

LoadedModule[14]=C:\Windows\system32\WS2_32.dll

LoadedModule[15]=C:\Windows\system32\NSI.dll

LoadedModule[16]=D:\image_processing\gmic\gmic_win64\libssh2-1__.dll

LoadedModule[17]=D:\image_processing\gmic\gmic_win64\LIBEAY32__.dll

LoadedModule[18]=D:\image_processing\gmic\gmic_win64\zlib1__.dll

LoadedModule[19]=D:\image_processing\gmic\gmic_win64\SSLEAY32.dll

LoadedModule[20]=D:\image_processing\gmic\gmic_win64\zlib1.dll

LoadedModule[21]=C:\Windows\system32\WLDAP32.dll

LoadedModule[22]=D:\image_processing\gmic\gmic_win64\libfftw3-3.dll

LoadedModule[23]=D:\image_processing\gmic\gmic_win64\libjpeg-9.dll

LoadedModule[24]=D:\image_processing\gmic\gmic_win64\libpng16-16.dll

LoadedModule[25]=D:\image_processing\gmic\gmic_win64\libtiff-5.dll

LoadedModule[26]=D:\image_processing\gmic\gmic_win64\liblzma-5__.dll

LoadedModule[27]=D:\image_processing\gmic\gmic_win64\libgcc_s_seh-1.dll

LoadedModule[28]=C:\Windows\system32\SHELL32.dll

LoadedModule[29]=C:\Windows\system32\SHLWAPI.dll

LoadedModule[30]=D:\image_processing\gmic\gmic_win64\libgomp-1.dll

LoadedModule[31]=D:\image_processing\gmic\gmic_win64\libwinpthread-1.dll

LoadedModule[32]=D:\image_processing\gmic\gmic_win64\libstdc++-6.dll

LoadedModule[33]=D:\image_processing\gmic\gmic_win64\libopencv_core2410.dll

LoadedModule[34]=D:\image_processing\gmic\gmic_win64\libopencv_highgui2410.dll

LoadedModule[35]=C:\Windows\system32\AVICAP32.dll

LoadedModule[36]=C:\Windows\system32\WINMM.dll

LoadedModule[37]=C:\Windows\system32\VERSION.dll

LoadedModule[38]=C:\Windows\system32\MSVFW32.dll

LoadedModule[39]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.18837_none_a4d981ff711297b6\COMCTL32.dll

LoadedModule[40]=C:\Windows\system32\AVIFIL32.dll

LoadedModule[41]=C:\Windows\system32\ole32.dll

LoadedModule[42]=C:\Windows\system32\MSACM32.dll

LoadedModule[43]=C:\Windows\system32\OLEAUT32.dll

LoadedModule[44]=C:\Windows\system32\IMM32.DLL

LoadedModule[45]=C:\Windows\system32\MSCTF.dll

State[0].Key=Transport.DoneStage1

State[0].Value=1

State[1].Key=DataRequest

State[1].Value=Bucket=176074141/nBucketTable=28/nResponse=1/n

FriendlyEventName=Stopped working

ConsentKey=APPCRASH

AppName=gmic.exe

AppPath=D:\image_processing\gmic\gmic_win64\gmic.exe

**Comment by jayprich** [comment] 2016-03-18 08:43
the line "Sig[6].Value=c0000005" signifies an access violation during the
call to msvcrt runtime library function

given that gmic's help command is in the process of printing output to the
console perhaps the string being printed had incorrect
length/format/encoding somehow internally .. but that's a guess

have you tried different terminal programs e.g. mintty or piping to a file?

**Comment by dtschump** [comment] 2016-03-18 10:03
Just tested here 
    
    $ ./gmic.exe -h

on my MSYS console on Win7, and the help displays until the end without any issue.
Damn, if I can't reproduce the bug, that will be hard for me to fix it :(

**Comment by dtschump** [comment] 2016-04-16 08:17
As I didn't get more info on that issue and cannot reproduce it, I'm closing it.

**Closed by dtschump** 2016-04-16 08:17 UTC
