### ISSUE TITLE
[√resolved] [Bug] GMIC-Qt,Colorize lineart [smart coloring]

### ISSUE THREAD

**Issue by SenlinOS** [dtschump/gmic-community#69] opened 2017-03-05 08:48 UTC
GMIC-Qt
Black & whtie > Colorize lineart [smart coloring] > color spots on transparent top layer.
The filled color parameters are different from the reference colors.
Color parameters are slightly different.
(You can use the eyedropper tool to view color parameters.)

Use software: gmic_ubuntu_xenial_amd64.deb (2.0.0_pre#170303)、GIMP 2.8.16、GIMP2.9.X

![Gqt](http://i.imgur.com/1Y9Uakn.jpg)

**Comment by dtschump** [comment] 2017-03-06 16:30
Hello. Didn't succeed in reproducing the problem here, tried both with GTK and Qt-based versions of the G'MIC plug-in for GIMP (2.8.16).
I get this : http://imgur.com/a/oz84Y

(first image : result, second image : input).
All looks fine for me.

Could you provide maybe a .xcf file that reproduces the issue when the smart colorize filter is run on it ?
Thanks!

**Comment by SenlinOS** [comment] 2017-03-07 02:07
GMIC in GIMP2.8.16, GTK and QT can run, but the QT version has a different color problems.GTK version is perfect.
GMIC-QT_GIMP2_8_16-XCF and VIDE: 
https://drive.google.com/file/d/0B2AXDet3w4pwVWR5Y3ZrQURYbzA/view?usp=sharing

GMIC in GIMP2.9.5, QT can run, but the QT version also has a different color problems. GTK version running crash (GIMP2.9.5 is the development version,not discuss it.)

**Comment by dtschump** [comment] 2017-03-07 08:03
Thanks for the very useful material and video. I've been able to reproduce the problem indeed.
Need some investigation for sure :)
Thanks !

**Comment by dtschump** [comment] 2017-03-07 13:10
We've finally found the bug, due to float to integer rounding issues.
This should be fixed now, after a filter update.
Thanks again for your report !

**Comment by SenlinOS** [comment] 2017-03-11 08:02
Installed the latest version, the problem has been resolved.
gmic_ubuntu_xenial_amd64.deb (2.0.0_pre, 10-Mar-2017)

Great！Great！Great！

**Comment by dtschump** [comment] 2017-03-11 09:46
Fine :)
Actually, there was no need to install the latest binary, just push the 'update filter' button and this would have fixed the issue as well.

**Closed by dtschump** 2017-03-11 09:46 UTC
